# config/packages/notifier.yaml
framework:
    notifier:
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'
            sms: 'twilio://AC5c28f160692174a4cc193d140aea920a:22bf38e536c7df7d4898bb0b7df308c0@default?from=+13312096972'
